[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  # Define which paths this setting applies to
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=60"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"